### ISSUE TITLE
聊天事件脚本未触发

### ISSUE THREAD

**Issue by t880216t** [AyaseCore/mod-LuaEngine#2]
脚本：
``` 
function chat()
    print("+++++++++++++here")
end
RegisterPlayerEvent(18, chat)
```
角色说话，没有触发脚本事件。

**Comment by AyaseCore** [comment]
fix in https://github.com/AyaseCore/azerothcore-wotlk/commit/2d9fc68e3849392d757cfe5bac336e40405a6e34
