### ISSUE TITLE
PerformIngameSpawn函数无效

### ISSUE THREAD

**Issue by t880216t** [AyaseCore/mod-LuaEngine#4]
创建npc 和 gameobject 无效，
脚本：
``` js
local x,y,z,o = player:GetLocation()
local m = player:GetMapId()
PerformIngameSpawn(1, 5420, m,player:GetInstanceId(), x, y, z, o, true, 0, 1)
```
没有效果

**Comment by AyaseCore** [comment]
据我所知这个不是用于创建npc或gob的 当然我不肯定 因为没用过
创建gob应该用 [SummonGameObject](http://uiwow.cc:88/eluna/WorldObject/SummonGameObject.html)
创建npc应该用[SpawnCreature](http://uiwow.cc:88/eluna/WorldObject/SpawnCreature.html)

**Comment by t880216t** [comment]
多谢回复，能给个小例子不，worldobject不知道咋传额。

**Comment by AyaseCore** [comment]
player:SummonGameObject 就行

**Comment by t880216t** [comment]
@AyaseCore 
试了player:SummonGameObject，的确能够立刻生成，但过一会就消失了。
另外，又试了试PerformIngameSpawn，是能创建的对象的，但是要重启服务器才能看到东西，能帮忙分析下不。

**Comment by AyaseCore** [comment]
lua的api我不太了解 我用的很少 一般都直接c+里写的
SummonGameObject是临时召唤 数据不保存数据库 平常用的比较多 这个重启后就没了
PerformIngameSpawn没用过 不过看你说的应该在数据库插入了数据 所以重启后还在

在我看来 写ai或者功能之类的一般只需要临时召唤就行了
如果要长期召唤直接gm命令更快
