### ISSUE TITLE
新建人物PLAYER_EVENT_ON_CHARACTER_CREATE事件无效

### ISSUE THREAD

**Issue by t880216t** [AyaseCore/mod-LuaEngine#6]
脚本：
local function test(event, player)
    print('新建任务事件')
end
RegisterPlayerEvent(1, test)

结果：
没有效果

**Comment by AyaseCore** [comment]
![image](https://user-images.githubusercontent.com/5546244/42045837-214f5dac-7b2f-11e8-8ee5-f99b68fcf7b1.png)
测试没问题
